# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-6svOqSUoM7SWxWnGBvp0Hbi_t927k6
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Load dataset
data = pd.read_csv("/content/heart.csv")

# Features and target
X = data.drop("output", axis=1)
y = data["output"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# MLP model
model = MLPClassifier(
    hidden_layer_sizes=(50, 25),
    max_iter=1000,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Test
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Dataset shape:", data.shape)
print(f"Accuracy: {accuracy * 100:.2f}%")

# =========================================================
# ❤️ HEART DISEASE PREDICTION USING MLP NEURAL NETWORK
# Google Colab - Complete Code
# =========================================================

# 1. IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

# =========================================================
# 2. UPLOAD heart.csv
# =========================================================

print("Upload your heart.csv file:")
uploaded = files.upload()

# Automatically find uploaded CSV
filename = list(uploaded.keys())[0]

# Load dataset
data = pd.read_csv(filename)

print("\n✅ Dataset loaded successfully!")
print("Dataset size:", data.shape)

display(data.head())

# =========================================================
# 3. CHECK DATA
# =========================================================

print("\n📋 Columns:")
print(data.columns.tolist())

print("\n❓ Missing values:")
print(data.isnull().sum())

# =========================================================
# 4. FEATURES AND TARGET
# =========================================================

X = data.drop("output", axis=1)
y = data["output"]

print("\nFeatures:", X.shape[1])
print("Target: output")

# =========================================================
# 5. TRAIN / TEST SPLIT
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# =========================================================
# 6. STANDARDIZATION
# =========================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =========================================================
# 7. MLP NEURAL NETWORK
# =========================================================

model = MLPClassifier(
    hidden_layer_sizes=(50, 25),
    activation="relu",
    solver="adam",
    max_iter=1000,
    random_state=42
)

print("\n🧠 Training MLP model...")

model.fit(X_train_scaled, y_train)

print("✅ Model training completed!")

# =========================================================
# 8. PREDICTION
# =========================================================

y_pred = model.predict(X_test_scaled)

# =========================================================
# 9. ACCURACY
# =========================================================

accuracy = accuracy_score(y_test, y_pred)

print("\n================================")
print("📊 MODEL PERFORMANCE")
print("================================")

print(f"Accuracy: {accuracy * 100:.2f}%")

# =========================================================
# 10. CLASSIFICATION REPORT
# =========================================================

print("\n📋 Classification Report:")
print(classification_report(y_test, y_pred))

# =========================================================
# 11. CONFUSION MATRIX
# =========================================================

cm = confusion_matrix(y_test, y_pred)

print("\n🔲 Confusion Matrix:")

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()
plt.title("Heart Disease Prediction - MLP")
plt.show()

# =========================================================
# 12. SAMPLE PATIENT PREDICTION
# =========================================================

patient = X.iloc[0].values.reshape(1, -1)

patient_scaled = scaler.transform(patient)

prediction = model.predict(patient_scaled)[0]

probability = model.predict_proba(patient_scaled)[0]

print("\n================================")
print("🩺 SAMPLE PATIENT PREDICTION")
print("================================")

if prediction == 1:
    print("⚠️ Prediction: Higher likelihood of heart disease")
else:
    print("✅ Prediction: Lower likelihood of heart disease")

print("\nProbability:")
print(f"No disease : {probability[0] * 100:.2f}%")
print(f"Disease    : {probability[1] * 100:.2f}%")

# =========================================================
# 13. ACTUAL VS PREDICTED
# =========================================================

results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print("\n================================")
print("🔍 ACTUAL VS PREDICTED")
print("================================")

display(results.head(20))

print("\n🎉 COMPLETE!")

