# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-6svOqSUoM7SWxWnGBvp0Hbi_t927k6
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Load dataset
data = pd.read_csv("/content/heart.csv")

# Features and target
X = data.drop("output", axis=1)
y = data["output"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# MLP model
model = MLPClassifier(
    hidden_layer_sizes=(50, 25),
    max_iter=1000,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Test
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Dataset shape:", data.shape)
print(f"Accuracy: {accuracy * 100:.2f}%")