# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e62QS7p5-g2b9YOgv0osqXN-FH3NPeLK
"""

import streamlit as st
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score


st.title("❤️ Heart Disease Prediction")

data = pd.read_csv("/content/heart.csv")

X = data.drop("output", axis=1)
y = data["output"]

st.write("Dataset loaded successfully!")
st.write(data.head())

from google.colab import drive
drive.mount('/content/drive')